strategy:
  matrix:
    # Ubuntu
    Ubuntu_Python35:
      imageName: 'ubuntu-16.04'
      pythonVer: '3.5'
    Ubuntu_Python36:
      imageName: 'ubuntu-16.04'
      pythonVer: '3.6'
      runCoverage: 'true'
    Ubuntu_Python37:
      imageName: 'ubuntu-16.04'
      pythonVer: '3.7'
    # macOS
    macOS_Python35:
      imageName: 'macOS-10.14'
      pythonVer: '3.5'
    macOS_Python36:
      imageName: 'macOS-10.14'
      pythonVer: '3.6'
    macOS_Python37:
      imageName: 'macOS-10.14'
      pythonVer: '3.7'
    # Windows
    Windows_Python35:
      imageName: 'vs2017-win2016'
      pythonVer: '3.5'
    Windows_Python36:
      imageName: 'vs2017-win2016'
      pythonVer: '3.6'
    Windows_Python37:
      imageName: 'vs2017-win2016'
      pythonVer: '3.7'

pool:
  vmImage: $(imageName)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: $(pythonVer)
    architecture: 'x64'
- script: python -m pip install --upgrade pip setuptools wheel
  displayName: Update pip
- script: python -m pip install -e .[dev]
  displayName: Install water_demand
- script: python -m pytest -v
  displayName: Unit tests
- script: python -m flake8
  displayName: flake8 tests
- script: python -m pytest --cov
  displayName: Run coverage
  condition: eq(variables['runCoverage'], 'true')
- script: bash <(curl https://codecov.io/bash) -t c643cd07-1ce3-41ed-a452-875968d4dcbb
  displayName: Upload to codecov
  condition: eq(variables['runCoverage'], 'true')